-- Seed data extracted from superdesign-export HTML designs
-- Run after initial migration

insert into public.projects (slug, title, description, tags, metric, href, featured) values
  ('tokencast', 'TokenCast', 'Design token pipeline broadcasting Figma variables to code — keeping design systems in sync across web and mobile platforms.', array['Design Tokens', 'Figma', 'Storybook'], '200+ components', '/work', true),
  ('mcp-atlas', 'MCP Atlas', 'A visual directory and discovery layer for Model Context Protocol servers — helping developers find, evaluate, and integrate MCP tools.', array['MCP', 'React', 'TypeScript'], 'Open Source', '/work', true),
  ('forgekit-mcp', 'ForgeKit MCP', 'Model Context Protocol server integrating Figma designs as structured context for AI coding assistants like Cursor and Claude Desktop.', array['MCP', 'Figma', 'Design Systems'], '5,703+ npm installs', '/projects/forgekit-mcp', true),
  ('storybook-system', 'Storybook System', 'Enterprise design system with 200+ components, Chromatic visual regression, and Figma Code Connect across 8 consumer apps.', array['Storybook', 'Chromatic', 'React'], '200+ components', '/case-studies/design-system-scale', true),
  ('nx-monorepo-scale', 'Nx Monorepo Scale', 'Scaled from 3 apps to 40+ packages across 12 product teams with shared design system, auth, and data layers.', array['Nx', 'Monorepo', 'CI/CD'], '65% faster CI', '/case-studies/nx-monorepo', true),
  ('flagship-mobile', 'Flagship Mobile App', 'React Native platform serving 500K+ users with shared design tokens, OTA updates, and monorepo parity with web.', array['React Native', 'Expo', 'Mobile'], '500K+ users', '/insights/shipping-react-native-at-scale', false),
  ('tanstack-migration', 'TanStack Migration', 'Full-stack React migration to TanStack Start with file-based routing, SSR, and Cloudflare Workers deployment.', array['TanStack Start', 'SSR', 'Cloudflare'], 'Framework', '/insights/mastering-tanstack-start', false),
  ('figma-design-pipeline', 'Figma Design Pipeline', 'Automated Figma-to-code pipeline with token sync, component mapping, and MCP context for AI coding assistants.', array['Figma', 'MCP', 'Tokens'], 'AI-native', '/projects/forgekit-mcp', false)
on conflict (slug) do nothing;

insert into public.articles (slug, title, excerpt, category, published_at, read_time, featured, content) values
  ('the-model-context-protocol', 'The Model Context Protocol: A Frontend Engineer''s Guide', 'How MCP is reshaping the hand-off between design tools and AI-native development workflows.', 'Featured Analysis', '2024-03-12', '12 min', true, array['The Model Context Protocol (MCP) represents a fundamental shift in how frontend engineers interact with AI coding assistants.', 'For years, the hand-off was the most friction-filled part of our work. With MCP, the hand-off disappears.', 'MCP represents a shift from AI as an external generator to AI as an integrated team member.']),
  ('architecting-for-100-on-lighthouse', 'Architecting for 100 on Lighthouse: The Airbnb Playbook', 'Performance budgets, code splitting strategies, and the infrastructure decisions that keep Core Web Vitals green.', 'Performance', '2024-02-28', '8 min', false, array['Achieving consistent Lighthouse scores requires architectural decisions from day one.', 'At scale, the biggest wins come from reducing JavaScript shipped to the client.']),
  ('storybook-to-next-js-playgrounds', 'From Storybook to Next.js Playgrounds', 'Bridging isolated component development with full-page integration testing using composable playground patterns.', 'Design Systems', '2024-02-14', '10 min', false, array['Storybook excels at component isolation, but teams need full-page contexts to validate real integration behavior.', 'Next.js playgrounds provide the missing layer.']),
  ('the-case-for-the-t-shaped-principal-engineer', 'The Case for the T-Shaped Principal Engineer in 2024', 'Why depth in frontend architecture plus breadth across design, product, and platform creates outsized impact.', 'Leadership', '2024-01-22', '7 min', false, array['The T-shaped principal engineer combines deep frontend expertise with enough breadth to connect design systems, platform engineering, and product strategy.']),
  ('llm-agents-in-the-monorepo', 'LLM Agents in the Monorepo: A 48-Hour Migration Story', 'How we used AI agents to migrate 1,942 components across an Nx monorepo with 88% automated test pass rate.', 'AI Engineering', '2023-12-18', '15 min', false, array['The biggest hurdle was not the LLM logic — it was the context window.', 'By the end of the 48-hour sprint, we generated 1,942 successful PRs.']),
  ('mastering-tanstack-start', 'Mastering TanStack Start: Full-Stack React Without the Framework Tax', 'File-based routing, server functions, and Cloudflare Workers deployment for modern portfolio and SaaS apps.', 'Frameworks', '2023-12-10', '11 min', false, array['TanStack Start brings together Router, Query, and server-side rendering in a composable package.']),
  ('shipping-react-native-at-scale', 'Shipping React Native at Scale: Lessons from 500K+ Users', 'Monorepo strategies, OTA updates, and design system parity between web and mobile at enterprise scale.', 'Mobile Development', '2023-12-05', '9 min', false, array['Shipping React Native at scale requires treating mobile as a first-class platform in your monorepo.'])
on conflict (slug) do nothing;

insert into public.testimonials (quote, author, role, company) values
  ('Rich transformed our frontend architecture from a collection of apps into a cohesive platform. His Nx monorepo work saved us months of refactoring.', 'Sarah Chen', 'VP of Engineering', 'Series B SaaS'),
  ('ForgeKit MCP is a game-changer for design-to-code workflows. 5,700+ installs in months. Rich''s focus on developer experience is evident in every API.', 'Marcus Webb', 'Staff Engineer', 'Design Tools Co'),
  ('The design system Rich built scaled from 20 to 200+ components without breaking consumer apps. Storybook + Chromatic integration was flawless.', 'Elena Rodriguez', 'Design Systems Lead', 'Enterprise Platform'),
  ('Rich doesn''t just write code — he architects systems that teams can actually maintain. His documentation and onboarding materials are exceptional.', 'James Park', 'Engineering Director', 'FinTech Startup');
